### ISSUE TITLE
Just a query not an issue

### ISSUE THREAD

**Issue by vishnucool220** [pavelvasev/qmlweb.components#4]
In /ComboBox.qml
In function init() 
//May i know what does this line does?what is the use of this?
    self.dom.style.pointerEvents = "auto";
Can you please explain what "dom" does? Thanks

**Comment by pavelvasev** [comment]
It allows this dom element to accept mouse events. We have to specify it explicitly, because qmlweb disables them by default.

**Comment by pavelvasev** [comment]
"dom" field is a html dom element, created by qmlweb for this qml element.

**Comment by vishnucool220** [comment]
Thanks for the quick reply :+1:
