### ISSUE TITLE
Testing on Chrome

### ISSUE THREAD

**Issue by brunoluvizotto** [pavelvasev/qmlweb.components#5]
Hello!

Very nice job you and the others are doing on qmlweb. It can be something awesome - if doesn't die! :)
Anyway, I was trying to test it following your instructions (two sibling directories, and then open qmlweb.components/src/test/test_run.html) and it's not working. All I get is a white rectangle with black border. I'm trying it on Chrome on Windows.

Any idea on what could be the problem?

Thanks!

**Comment by pavelvasev** [comment]
Hi Brudju!

I updated the readme and added one more step:

```
II. Configure your browser to allow ajax requests to local files.
Chrome command line arg: --allow-file-access-from-files
```

Also you may try online version: http://pavelvasev.github.io/qmlweb.run/

**Comment by brunoluvizotto** [comment]
Awesome! It's working now. :)
Keep going with the good work!
